### ISSUE TITLE
When the token of a selloffer no longer is available, it isn't removed from active selloffers

### ISSUE THREAD

**Issue by Crelde** [benber86/nft_royalties_market#3]
https://github.com/benber86/nft_royalties_market/blob/main/contracts/Marketplace.sol
```
        // If, for some reason, the token is not approved anymore (transfer or
        // sale on another market place for instance), we remove the sell order
        // and throw
        if (token.getApproved(tokenId) != address(this)) {
            delete (activeSellOffers[tokenId]);
            // Broadcast offer withdrawal
            emit SellOfferWithdrawn(tokenId, seller);
            // Revert
            revert("Invalid sell offer");
        }
```
Hey, I am pretty sure that the event will never fire and the selloffer will not be deleted when you revert here.
I guess an alternative would be to send back the value that was sent and remove the revert and put the rest of the code in the purchase method in an else block?

**Comment by Crelde** [comment]
https://github.com/benber86/nft_royalties_market/blob/main/contracts/Marketplace.sol

**Comment by benber86** [comment]
Thanks for catching this!
